### ISSUE TITLE
in issue #1 there is an error in the title

### ISSUE THREAD

**Issue by jvalle** [jvalle/seriousbiz-game-per-month-ed#2]
the title reads "in the description the is an error"
should read "in the description there is an error"
assigning to @fponticelli

**Comment by fponticelli** [comment]
you cannot assign it to me ... I believe it is illegal!

Il giorno Mon Jan 05 2015 at 1:36:36 PM jvalle notifications@github.com
ha scritto:

**Comment by fponticelli** [comment]
bug on bug #1 is fixed .... closing.
